"""Training script for ContactTCN.

Trains the causal TCN contact detector on labeled pose sequences.
The model outputs raw logits; ``BCEWithLogitsLoss`` is used for
numerical stability (no sigmoid in the model forward pass).

Usage
-----
.. code-block:: bash

    python -m myogait.training.train_contact_tcn \\
        --data /path/to/labeled_sequences/ \\
        --output ~/.myogait/contact_tcn.pt \\
        [--epochs 50] [--batch-size 16] [--lr 1e-3] \\
        [--window 24] [--channels 32] [--n-dilations 3]

Input data format
-----------------
A directory of ``.npz`` files.  Each file must contain:

``features``
    ``np.ndarray``, shape ``(T, N_FEATURES)`` where N_FEATURES=17.
    Produced by :func:`myogait.detectors.learned_contact_detector.build_features`.

``labels``
    ``np.ndarray``, shape ``(T,)``, dtype float32, values in {0.0, 1.0}.
    ``1.0`` = foot in contact with ground, ``0.0`` = airborne.

.. note::
   Dummy/synthetic sequences generated by ``generate_dummy_dataset.py``
   are suitable for smoke-testing the training loop, **not** for
   validating model quality.  Report metrics only on real annotated data.

Checkpoint format
-----------------
::

    {
        "state_dict": OrderedDict(...),
        "n_features": int,
        "channels":   int,
        "kernel_size": int,
        "n_dilations": int,
        "val_f1":     float,   # best validation F1
        "epoch":      int,
    }
"""

from __future__ import annotations

import argparse
import logging
import random
import sys
from pathlib import Path
from typing import List, Tuple

import numpy as np

logger = logging.getLogger(__name__)


# --------------------------------------------------------------------------- #
# Dataset                                                                       #
# --------------------------------------------------------------------------- #

class _ContactDataset:
    """Sliding-window dataset over a collection of labeled sequences.

    Parameters
    ----------
    npz_files : list of Path
        Labeled sequence files (each has 'features' and 'labels' arrays).
    window : int
        Window length in frames.
    """

    def __init__(self, npz_files: List[Path], window: int) -> None:
        self.window = window
        self._windows: List[Tuple[np.ndarray, np.ndarray]] = []

        for path in npz_files:
            data = np.load(str(path))
            feats = data["features"].astype(np.float32)   # (T, F)
            labels = data["labels"].astype(np.float32)    # (T,)
            T = len(feats)
            if T < window:
                continue
            for start in range(T - window + 1):
                self._windows.append((
                    feats[start: start + window],   # (window, F)
                    labels[start: start + window],  # (window,)
                ))

    def __len__(self) -> int:
        return len(self._windows)

    def __getitem__(self, idx: int) -> Tuple[np.ndarray, np.ndarray]:
        return self._windows[idx]


def _collate(batch: List[Tuple[np.ndarray, np.ndarray]]):
    """Stack a list of (features, labels) tuples into tensors."""
    import torch
    feats  = torch.from_numpy(np.stack([b[0] for b in batch]))   # (B, W, F)
    labels = torch.from_numpy(np.stack([b[1] for b in batch]))   # (B, W)
    return feats, labels


def _make_loader(files: List[Path], window: int, batch_size: int, shuffle: bool):
    """Create a simple batched loader without DataLoader dependencies."""
    ds = _ContactDataset(files, window)
    indices = list(range(len(ds)))
    if shuffle:
        random.shuffle(indices)

    def _iter():
        batch = []
        for i in indices:
            batch.append(ds[i])
            if len(batch) == batch_size:
                yield _collate(batch)
                batch = []
        if batch:
            yield _collate(batch)

    return _iter, len(ds)


# --------------------------------------------------------------------------- #
# Metrics                                                                       #
# --------------------------------------------------------------------------- #

def _binary_metrics(
    logits: "torch.Tensor",
    labels: "torch.Tensor",
    threshold: float = 0.5,
) -> Tuple[float, float, float]:
    """Return (accuracy, precision, recall, F1) for binary classification.

    Returns
    -------
    tuple
        (accuracy, f1) — both in [0, 1].
    """
    import torch
    preds = (torch.sigmoid(logits) >= threshold).float()
    tp = ((preds == 1) & (labels == 1)).sum().item()
    fp = ((preds == 1) & (labels == 0)).sum().item()
    fn = ((preds == 0) & (labels == 1)).sum().item()
    tn = ((preds == 0) & (labels == 0)).sum().item()

    acc = (tp + tn) / max(tp + tn + fp + fn, 1)
    prec = tp / max(tp + fp, 1)
    rec  = tp / max(tp + fn, 1)
    f1   = 2 * prec * rec / max(prec + rec, 1e-8)
    return float(acc), float(f1)


# --------------------------------------------------------------------------- #
# Training loop                                                                 #
# --------------------------------------------------------------------------- #

def train(
    data_dir: Path,
    output_path: Path,
    epochs: int = 50,
    batch_size: int = 16,
    lr: float = 1e-3,
    window: int = 24,
    channels: int = 32,
    kernel_size: int = 3,
    n_dilations: int = 3,
    val_split: float = 0.2,
    seed: int = 42,
) -> None:
    """Run the training loop.

    Parameters
    ----------
    data_dir : Path
        Directory containing labeled ``.npz`` sequence files.
    output_path : Path
        Destination for the best-val-F1 checkpoint.
    epochs : int
        Number of training epochs.
    batch_size : int
        Mini-batch size.
    lr : float
        Adam learning rate.
    window : int
        Sliding window length in frames.
    channels : int
        TCN channel width.
    kernel_size : int
        TCN temporal kernel size.
    n_dilations : int
        Number of TCN blocks (dilation doubles each block).
    val_split : float
        Fraction of files reserved for validation.
    seed : int
        Random seed for reproducibility.
    """
    try:
        import torch
        import torch.nn as nn
    except ImportError:
        logger.error("PyTorch is required for training: pip install torch")
        sys.exit(1)

    try:
        from myogait.detectors.contact_tcn import ContactTCN
        from myogait.detectors.learned_contact_detector import N_FEATURES, FEATURE_SCHEMA
    except ImportError:
        # Allow running as a standalone script from the repo root
        sys.path.insert(0, str(Path(__file__).parent.parent.parent))
        from myogait.detectors.contact_tcn import ContactTCN
        from myogait.detectors.learned_contact_detector import N_FEATURES, FEATURE_SCHEMA

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    # Collect .npz files
    all_files = sorted(data_dir.glob("*.npz"))
    if not all_files:
        logger.error("No .npz files found in %s", data_dir)
        sys.exit(1)

    # Validate feature dimensionality of the first file
    _sample = np.load(str(all_files[0]))
    if "features" not in _sample or "labels" not in _sample:
        logger.error(
            "File %s is missing 'features' or 'labels' arrays. "
            "Expected keys: features (T, %d), labels (T,).",
            all_files[0].name, N_FEATURES,
        )
        sys.exit(1)
    actual_f = _sample["features"].shape[1] if _sample["features"].ndim == 2 else -1
    if actual_f != N_FEATURES:
        logger.error(
            "Feature dimension mismatch in %s: got %d, expected %d.\n"
            "Feature schema: %s",
            all_files[0].name, actual_f, N_FEATURES, list(FEATURE_SCHEMA),
        )
        sys.exit(1)
    logger.info("Feature schema validated: %d features × %s", N_FEATURES, list(FEATURE_SCHEMA))

    random.shuffle(all_files)
    n_val = max(1, int(len(all_files) * val_split))
    val_files   = all_files[:n_val]
    train_files = all_files[n_val:]

    logger.info(
        "Dataset: %d train files, %d val files (window=%d)",
        len(train_files), len(val_files), window,
    )

    model = ContactTCN(
        n_features=N_FEATURES,
        channels=channels,
        kernel_size=kernel_size,
        n_dilations=n_dilations,
    )
    logger.info(
        "ContactTCN: %d params, receptive field = %d frames",
        model.param_count(), model.receptive_field,
    )

    criterion = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    best_val_f1 = -1.0
    output_path.parent.mkdir(parents=True, exist_ok=True)

    for epoch in range(1, epochs + 1):
        # ---- Training ----
        model.train()
        train_loader, _ = _make_loader(train_files, window, batch_size, shuffle=True)
        train_loss = 0.0
        n_train_batches = 0

        for feats, labels in train_loader():
            optimizer.zero_grad()
            logits = model(feats)               # (B, window)
            loss = criterion(logits, labels)
            loss.backward()
            optimizer.step()
            train_loss += loss.item()
            n_train_batches += 1

        avg_train_loss = train_loss / max(n_train_batches, 1)

        # ---- Validation ----
        model.eval()
        val_loader, _ = _make_loader(val_files, window, batch_size, shuffle=False)
        all_logits: list = []
        all_labels: list = []

        with torch.no_grad():
            for feats, labels in val_loader():
                logits = model(feats)
                all_logits.append(logits.reshape(-1))
                all_labels.append(labels.reshape(-1))

        if all_logits:
            val_logits_cat = torch.cat(all_logits)
            val_labels_cat = torch.cat(all_labels)
            val_acc, val_f1 = _binary_metrics(val_logits_cat, val_labels_cat)
            val_loss = float(criterion(val_logits_cat, val_labels_cat).item())
        else:
            val_acc = val_f1 = val_loss = 0.0

        logger.info(
            "Epoch %3d/%d | train_loss=%.4f | val_loss=%.4f "
            "val_acc=%.3f val_f1=%.3f%s",
            epoch, epochs, avg_train_loss, val_loss, val_acc, val_f1,
            " [best]" if val_f1 > best_val_f1 else "",
        )

        if val_f1 > best_val_f1:
            best_val_f1 = val_f1
            checkpoint = {
                "state_dict":     model.state_dict(),
                "n_features":     N_FEATURES,
                "channels":       channels,
                "kernel_size":    kernel_size,
                "n_dilations":    n_dilations,
                # feature_schema is stored in the checkpoint so that the
                # inference code can warn if the extractor has changed since
                # training (see _validate_checkpoint_schema in detector).
                "feature_schema": list(FEATURE_SCHEMA),
                "val_f1":         best_val_f1,
                "epoch":          epoch,
            }
            torch.save(checkpoint, str(output_path))

    logger.info("Training complete. Best val F1=%.4f. Saved to %s", best_val_f1, output_path)


# --------------------------------------------------------------------------- #
# CLI                                                                           #
# --------------------------------------------------------------------------- #

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Train ContactTCN for foot contact detection.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--data",       type=Path, required=True,
                   help="Directory of labeled .npz sequence files.")
    p.add_argument("--output",     type=Path, default=Path.home() / ".myogait" / "contact_tcn.pt",
                   help="Output checkpoint path.")
    p.add_argument("--epochs",     type=int,   default=50)
    p.add_argument("--batch-size", type=int,   default=16)
    p.add_argument("--lr",         type=float, default=1e-3)
    p.add_argument("--window",     type=int,   default=24)
    p.add_argument("--channels",   type=int,   default=32)
    p.add_argument("--n-dilations",type=int,   default=3)
    p.add_argument("--val-split",  type=float, default=0.2)
    p.add_argument("--seed",       type=int,   default=42)
    return p


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s  %(levelname)-8s  %(message)s",
        datefmt="%H:%M:%S",
    )
    args = _build_parser().parse_args()
    train(
        data_dir=args.data,
        output_path=args.output,
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        window=args.window,
        channels=args.channels,
        kernel_size=args.kernel_size,
        n_dilations=args.n_dilations,
        val_split=args.val_split,
        seed=args.seed,
    )
